[alias]
build-android = [
    "ndk",
    "-t", "armeabi-v7a",
    "-t", "arm64-v8a",
    "-t", "x86",
    "-t", "x86_64",
    "-o", "../sentc_flutter/sentc/android/src/main/jniLibs",
    "build", "--release"
]